### ISSUE TITLE
terraform-inventory issue

### ISSUE THREAD

**Issue by fergfamster** [ldejager/terraform-mariadb-cluster#4]
Hello, the document seems to miss a part of the deployment. I downloaded and ran the terraform-inventory and it works fine in terms of calling it. However when using the deploy/playbook.yml export command im getting a parse failed error from the tfstate file? Is this something you have seen before? The terraform side itself works great. The disconnect is when I try to create the playbook.yml file using terraform-inventory. Im getting the following error just for your view:
$: ansible-playbook --inventory-file=terraform.tfstate deploy/playbook.yml
[WARNING]: * Failed to parse /*
/terraform-mariadb-cluster/terraform.tfstate with ini plugin:
*/terraform-mariadb-
cluster/terraform.tfstate:2: Expected key=value host variable assignment, got:
3,
[WARNING]: Unable to parse *
/terraform-mariadb-cluster/terraform.tfstate as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
ERROR! playbooks must be a list of plays

However when I run the terraform-inventory --list terraform.tfstate I do get the following:
{"%4":["54.82.253.204","54.173.45.87","54.152.14.48"],"db":["54.82.253.204","54.173.45.87","54.152.14.48"],"db.0":["54.82.253.204"],"db.1":["54.173.45.87"],"db.2":["54.152.14.48"],"dc_aws":["54.82.253.204","54.173.45.87","54.152.14.48"],"name_db-01":["54.82.253.204"],"name_db-02":["54.173.45.87"],"name_db-03":["54.152.14.48"],"role_dbhost":["54.82.253.204","54.173.45.87","54.152.14.48"],"sshuser*":["54.82.253.204","54.173.45.87","54.152.14.48"],"type_aws_instance":["54.82.253.204","54.173.45.87","54.152.14.48"]}

**Comment by ldejager** [comment]
Hi James, apologies I missed this issue completely and just happened to stumble onto this old repository. I assume you've resolved this in the meantime?

From the above output, the failed to parse message is ansible letting you know it doesn't know how to read the terraform state file and you'll need to point your ansible-playbook command to the terraform-inventory binary which processes the terraform state into an ansible compatible inventory.

For example;

```
ansible-playbook --sudo -u ec2-user -i ~/bin/terraform-inventory provisioning/terraform.yml
```

Again, apologies for the late response!
